### ROTA RAIZ (Teste se o servidor está on)
GET http://localhost:3000

### -------------------------------------------
### CLIENTES
### -------------------------------------------

### Criar Cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "nome": "João da Silva",
  "email": "joao@teste.com",
  "telefone": "1199999-8888"
}

### Listar Clientes
GET http://localhost:3000/clientes

### -------------------------------------------
### PRODUTOS
### -------------------------------------------

### Criar Produto 1
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Teclado Mecânico",
  "descricao": "Switch Blue, RGB",
  "preco": 150.00
}

### Criar Produto 2
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Mouse Gamer",
  "descricao": "12000 DPI",
  "preco": 89.90
}

### Listar Produtos
GET http://localhost:3000/produtos